POST http://localhost:8080/api/v1/item
Content-Type: application/json

{
    "text": "fuck",
    "done": true,
    "deadline": "2024-02-20"
}


###

DELETE http://localhost:8080/api/v1/item/1

###

PUT http://localhost:8080/api/v1/item/1?text=suck

###

POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "userName": "Oguzhan",
    "password": "123456"
}

###
POST http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json

{
    "userName": "Oguzhan",
    "password": "123456"
}